# YAML
#
# ----------------------------------------------------------------------
# Bulk FNA download from BV-BRC's FTP server
#
# We will be downloading {virus_dir}/{familiy}.fna
#
# ----------------------------------------------------------------------
# https://www.bv-brc.org/docs/quick_references/ftp.html
sftp:
  server: ftp://ftp.bv-brc.org
  virus_dir: viruses
  user: anonymous:guest

# standard NGS tools Singularity image
sif: singularity exec /vol/patric3/production/containers/ubuntu-dev-160-build12-2.sif

